version: "3.9"
services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"   # (опционально) для HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env
    networks:
      - web
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    external: true

